# Generated by Django 3.2.16 on 2025-02-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_post_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='Post',
        ),
    ]
